name: Deploy QA

on:
  push:
    paths:
    - 'app-fr/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "app-fr/*.html,app-fr/*.js,app-fr/js/*.js,app-fr/js/jQuery-2.2.3/*.js,app-fr/image/*.jpeg,app-fr/image/*.jpg"
        target: "/opt/http-content/jftl2021/testbci/app-fr"
        rm: true
