name: Cerberus

on:
   workflow_run:
    workflows: ["Deploy website on QA"]
    branches: [main]
    types: 
      - completed

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./launchTest.sh
         ./launchTest.sh
      shell: bash
