name: Deploy website on QA and launch Campaign

on:
  push:
    paths:
      - 'website/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout source and build
      run: echo Hello, world!
  deploy_fr:
    needs: Build
    name: Deploy FR
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "website/*.html,website/*.js,website/js/*.js,website/js/jQuery-2.2.3/*.js,website/image/*.jpeg,website/image/*.jpg"
        target: "/opt/http-content/jftl2021/app-fr-test"
        strip_components: 1
        rm: true
  deploy_uk:
    needs: Build
    name: Deploy UK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "website/*.html,website/*.js,website/js/*.js,website/js/jQuery-2.2.3/*.js,website/image/*.jpeg,website/image/*.jpg"
        target: "/opt/http-content/jftl2021/app-uk-test"
        strip_components: 1
        rm: true
  run_tests:
    needs: [deploy_fr,deploy_uk]
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: |
         chmod +x ./launchTest.sh
         ./launchTest.sh -a ${{ github.event.pusher.name }} -h https://jftl2021.cerberus-testing.com -c Website_NonRegression_UAT
      shell: bash
